### ISSUE TITLE
Pulse type

### ISSUE THREAD

**Issue by mike42** [receipt-print-hq/escpos-printer-db#14]
Add a feature for pulse (aka 'cash draw kick-out') variations.

```yaml
feature:
  pulseStandard: true/false
  pulseBel: true/false
```

By my reading, most printers use the ESC p m t1 t2 ("pulse") command, while Citizen printers are using a single BEL character instead.

--

- http://keyhut.com/popopen.htm
- python-escpos/python-escpos#179
