### ISSUE TITLE
Oxhoo AF240 character identification

### ISSUE THREAD

**Issue by mike42** [receipt-print-hq/escpos-printer-db#44]
This POS display has a code page that identifies itself only as "Europe", and prints these characters:

![af-240-europe](https://user-images.githubusercontent.com/2080552/43356740-d07ef7f0-92b9-11e8-8990-6a3bf2818c7b.png)

The code page does not match any that `iconv` knows. I'm tracking this code page in the database as "OXHOO-EUROPEAN", on the assumption that it is vendor-specific.

The task here is to **identify each character and fill in the blanks**. I got this far defining it:

```yml
OXHOO-EUROPEAN:
  name: Oxhoo-specific European
  data:
    - "ÇüéâäàåçêëèïîìÄÅ"
    - "ÉæÆôöòûùÿÖÜñÑªº¿"
    - "áíóú¢£¥₧ƒ¡ÃãÕõØø"
    - "·¨°`´½¼×÷≤≥«»≠√¯"
    - "⌠⌡∞◤↵↑↓→←┌┐└┘•®©"
    # Some unidentified chars
    - "™†§¶Γ◢Θ         "
    - "ß   ε           "
    - "τ               "
```
